name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        graphql-version: [15.x, 16.x, ^17.0.0-alpha.3]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn
    - run: yarn build
    # We must build BEFORE we replace the GraphQL version (because otherwise the types don't match)
    - run: yarn add graphql@${{ matrix.graphql-version }}
    - run: yarn test
